### PR TITLE
register rev function

### LINKED ISSUE #64: Ambiguity error for `rev` with latest version of Symbolics

### PR DESCRIPTION
**Pull request by lucaferranti**
fixes #64

### CODE REVIEW

**Comment by lucaferranti** [comment]
mmmm 

```julia
julia> using ReversePropagation
[ Info: Precompiling ReversePropagation [527681c1-8309-4d3f-8790-caf822a419ba]
WARNING: Method definition promote_symtype(typeof(ReversePropagation.rev), Any...) in module ReversePropagation at C:\Users\lucaa\.julia\packages\Symbolics\WcP64\src\register.jl:82 overwritten on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **

**Comment by dpsanders** [comment]
I don't see that error with the latest versions of all the dependencies, in a fresh environment and with Julia 1.7.1.

**Comment by dpsanders** [comment]
I bumped the versions and made ReversePropagation 0.2.
Could you try this out please @lucaferranti ?

**Comment by dpsanders** [comment]
There are some deprecation warnings `Warning: Variable{T}(name, idx...) is deprecated, use variable(name, idx...; T=T) ` though, with Symbolics.jl v4. Would you have a chance to fix those?

**Comment by lucaferranti** [comment]
yes I'll check in the upcoming days

**Comment by dpsanders** [comment]
@lucaferranti : It looks like this is ready. Once it's green I'm planning to merge and release the new version

**Comment by lucaferranti** [comment]
great, thanks! Haven't had the time to do upstream tests with ICP.jl, but if it works here I guess it's fine to merge it now and debug possible further issues in ICP later

**Comment by dpsanders** [comment]
Many thanks @lucaferranti !

**Pull request merged**
